import type { Metadata } from 'next'

import { Open_Sans } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'

import { auth } from '@/auth'

import { ThemeProvider } from '@/providers/ThemeProvider'
import { ModalProvider } from '@/providers/ModalProvider'

import { Toaster } from '@/components/ui/sonner'

import { cn } from '@/lib/utils'

import './globals.css'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang='en' suppressHydrationWarning>
        <body className={cn(font.className)}>
          <ThemeProvider attribute='class' defaultTheme='dark'>
            {children}
            <ModalProvider />
            <Toaster position='top-center' />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
